server:
  port: 8082

logging:
  level:
    root: WARN
    com.it.cloud: debug
    org.springframework.web: debug
  pattern:
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} %5p -- [%t] %-40.40logger{39} : %m%n%xEx{10}'
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %5p -- [%t] %-40.40logger{39} : %m%n%xEx{10}'

#配置监控Actuator
#http://localhost:8081/actuator/metrics
#management:
#  endpoints:
#    web:
#      exposure:
#          # 暴露metrics端点，如需暴露多个，用,分隔；如需暴露所有端点，用'*'
#          include: metrics
#http://localhost:8081/actuator/health
management:
  endpoint:
    health:
      # 是否展示健康检查详情
      show-details: always

spring:
  application:
    # 指定注册到eureka server上的服务名称，对于电影微服务，本系列将名称设为microservice-consumer-movie
    name: microservice-provider-user

eureka:
  client:
    service-url:
      # 指定eureka server通信地址，注意/eureka/小尾巴不能少
#      defaultZone: http://localhost:8761/eureka/
      defaultZone: http://user:password123@localhost:8761/eureka/
  instance:
    # 是否注册IP到eureka server，如不指定或设为false，那就会注册主机名到eureka server
    prefer-ip-address: true


