server:
  port: 8081
logging:
  level:
    root: INFO
    org.springframework.cloud.sleuth: DEBUG
spring:
  application:
    name: microservice-sleuth-zipkin
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      # 采样率，模式0.1，也就是10%，为了便于观察效果，改为1.0，也就是100%。生产环境建议保持默认。
      probability: 1.0

      #zipkin 服务地址
      #使用https://search.maven.org/remote_content?g=io.zipkin.java&a=zipkin-server&v=LATEST&c=exec 下载最新版本的Zipkin Server，例如zipkin-server-2.11.3-exec.jar
      #启动Zipkin Server

      #java -jar zipkin-server-2.11.7-exec.jar
management:
  endpoints:
    web:
      exposure:
        # 开放所有监控端点
        include: '*'
  endpoint:
    health:
      # 是否展示健康检查详情
      show-details: always

eureka:
  client:
    service-url:
      # 指定eureka server通信地址，注意/eureka/小尾巴不能少
      defaultZone: http://user:password123@localhost:8761/eureka/
  instance:
    # 是否注册IP到eureka server，如不指定或设为false，那就会注册主机名到eureka server
    prefer-ip-address: true


