server:
  port: 8761


spring:
  security:
    user:
      name: user                # 配置登录的账号是user
      password: password123     # 配置登录的密码是password123
  application:
    name: microservice-discovery-eureka
eureka:
  client:
    # 是否要注册到其他Eureka Server实例
    register-with-eureka: false
    # 是否要从其他Eureka Server实例获取数据
    fetch-registry: false
    service-url:
      #      defaultZone: http://localhost:8761/eureka/
      defaultZone: http://user:password123@localhost:8761/eureka/
  # 关闭自我保护模式
#  server:
#    enableSelfPreservation: false


