server:
  port: 8010

logging:
  level:
    root: WARN
    com.it.cloud: debug
    org.springframework.web: debug
  pattern:
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} %5p -- [%t] %-40.40logger{39} : %m%n%xEx{10}'
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %5p -- [%t] %-40.40logger{39} : %m%n%xEx{10}'

spring:
  application:
    # 指定注册到eureka server上的服务名称
    name: microservice-consumer-movie

eureka:
  client:
    service-url:
      # 指定eureka server通信地址，注意/eureka/小尾巴不能少
#      defaultZone: http://localhost:8761/eureka/
      defaultZone: http://user:password123@localhost:8761/eureka/
  instance:
    # 是否注册IP到eureka server，如不指定或设为false，那就会注册主机名到eureka server
    prefer-ip-address: true

#默认情况下Ribbon是懒加载的——首次请求Ribbon相关类才会初始化，这会导致首次请求过慢的问题，你可以配置饥饿加载，让Ribbon在应用启动时就初始化。
ribbon:
  eager-load:
    enabled: true
    # 多个用,分隔
    clients: microservice-provider-user
# 访问查看状态http://localhost:8010/actuator/health
management:
  endpoint:
    health:
      # 是否展示健康检查详情
      show-details: always